apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo_test.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "todo_test.name" . }}
    helm.sh/chart: {{ include "todo_test.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.managePort }}
      targetPort: manage
      protocol: TCP
      name: manage
  selector:
    app.kubernetes.io/name: {{ include "todo_test.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if (gt .Values.replicaCount 1.0) }}
    todo_test: replicas
    {{- end }}
